scalar GraphQLDate

type CourseCategory {
  _id: ID!
  name: String!
}

input InstructorInput {
  name: String!
  photo: String
  excerpt: String
  bio: String
  courses: [ID!]!
}

type Instructor {
  _id: ID!
  name: String!
  photo: String
  excerpt: String
  bio: String
  courses: [Course!]!
}

input CourseInput {
  title: String!
  description: String!
  instructors: [ID!]!
  fee: Float
}

type Course {
  _id: ID!
  title: String!
  description: String!
  instructors: [Instructor!]!
  fee: Float
  category: CourseCategory!
}

type Schedule {
  _id: ID!
  course: Course!
  dates: [GraphQLDate!]!
}

type Student {
  _id: ID!
  name: String!
}

type Query {
  instructors: [Instructor]
  courseCategories: [CourseCategory]
  courses: [Course]
  schedules: [Schedule]
}

type Mutation {
  addInstructor(instructor: InstructorInput!): Instructor!
  updateInstructor(instructor: InstructorInput!): Instructor!
  addCourse(course: CourseInput!): Course!
  updateCourse(course: CourseInput!): Course!
}
